name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app

    # - name: Install SwiftLint
    #   run: brew install swiftlint
      
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project weather.xcodeproj \
          -scheme weather \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -testPlan WeatherUITests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -allowProvisioningUpdates | xcbeautify
          
    # Add additional checks
    # - name: Check Code Style
    #   run: |
    #     # Add SwiftLint or other style checks
    #     swiftlint lint
        
    - name: Check Code Coverage
      run: |
        # Add code coverage checks
        xcodebuild test \
          -project weather.xcodeproj \
          -scheme weather \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -enableCodeCoverage YES \
          | xcbeautify
