name: UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project weather.xcodeproj \
          -scheme weather \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          -testPlan WeatherUITests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
